- name: Set timezone to Europe/Moscow
  timezone:
    name: '{{ timezone }}'

- name: create JetBrains user
  user:
    name: '{{ jetbrains_user_name }}'
    uid: '{{ jetbrains_user_uid }}'
    groups: docker
    shell: /bin/bash
    comment: 'JetBrains service user'
  notify: restart docker

- name: Create directory to Docker
  file:
    path: '~{{ jetbrains_user_name }}/docker'
    owner: '{{ jetbrains_user_name }}'
    group: '{{ jetbrains_user_name }}'
    state: directory
    mode: 0750

- name: Create docker-compose.yml
  template:
    src: 'templates/docker-compose.yml.j2'
    dest: '~{{ jetbrains_user_name }}/docker/docker-compose.yml'
    owner: '{{ jetbrains_user_name }}'
    group: '{{ jetbrains_user_name }}'
    mode: 0750
  register: result

- name: Recreate YouTrack Docker
  shell: 'docker-compose rm -s -f && docker-compose up -d'
  args:
    chdir: '~{{ jetbrains_user_name }}/docker'
  when: result.changed
