- name: Ansible check youtrack jar exist
  stat:
    path: ~{{ youtrack_user }}/standalone/youtrack.jar
  register: youtrack_jar_file

- name: Download YouTrack Jar
  get_url:
    url: '{{ youtrack_jar }}'
    dest: '~{{ youtrack_user }}/standalone/youtrack.jar'
  when: not youtrack_jar_file.stat.exists

- name: Create youtrack init.d
  template:
    src: templates/youtrack_initd.j2
    dest: /etc/init.d/youtrack

- name: Create youtrack wrapper.conf
  template:
    src: templates/wrapper.conf.j2
    dest: '~{{ youtrack_user }}/standalone/conf/wrapper.conf'
